# config/model_params.yaml
lyapunov_model:
  v_param: 0.5  # Tradeoff between energy consumption and queue stability
  queue_drift_penalty: 0.1  # Penalty for queue length drift

dnn_model:
  learning_rate: 0.001
  batch_size: 64
  epochs: 100
  hidden_layers: [128, 64, 32]
  dropout_rate: 0.2